databases:
  - name: portfolio-db
    databaseName: portfolio_db
    user: portfolio_user
    plan: free

services:
  - type: web
    name: portfolio-backend
    runtime: docker
    dockerfilePath: ./portfolio-backend/Dockerfile
    dockerContext: ./portfolio-backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: portfolio-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FINNHUB_API_KEY
        value: d5u4k6hr01qtjet20al0d5u4k6hr01qtjet20alg
      - key: CORS_ALLOWED_ORIGINS
        value: https://portfolio-risk-analyzer-seven.vercel.app
      - key: SERVER_PORT
        value: "8081"
